apiVersion: v1
kind: ConfigMap
metadata:
    name: model-server-config-{{ .Values.configVersions.modelServer }}
    namespace: {{ .Values.namespace }}
    labels:
        app.kubernetes.io/name: model-server
        app.kubernetes.io/version: {{ .Values.configVersions.modelServer }}
        app.kubernetes.io/part-of: fastapi-app
data:
    model_server_url: "http://model-server-service:8000"
    model_name: {{ .Values.modelName }}