apiVersion: v1
kind: Service
metadata:
  name: model-server-service
  namespace: default  # Replace with your actual namespace
spec:
  selector:
    app: model-server  # Ensure this matches the labels in your model server deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP  # Change to LoadBalancer if external access is needed
