apiVersion: v1
kind: Secret
metadata:
    name: redis-secret-{{ .Values.configVersions.redis }}
    namespace: {{ .Values.namespace }}
    labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/version: {{ .Values.configVersions.redis }}
type: Opaque
data:
    db_password: {{ .Values.redis.password | b64enc }}