apiVersion: v1
kind: Service
metadata:
    name: redis-service
    namespace: {{ .Values.namespace }}
    labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: fastapi-app
        role: master
spec:
    ports:
        - name: redis
          port: 6379
          targetPort: 6379
    selector:
        app.kubernetes.io/name: redis
        role: master