apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
    namespace: {{ .Values.namespace }}
    labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: fastapi-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: redis
            role: master
    template:
        metadata:
            labels:
                app.kubernetes.io/name: redis
                role: master
        spec:
            volumes:
                - name: redis-storage
                  persistentVolumeClaim:
                      claimName: redis-pvc
            containers:
                - name: redis
                  image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
                  resources:
                      limits:
                          memory: {{ .Values.redis.resources.memory }}
                          cpu: {{ .Values.redis.resources.cpu }}
                  command:
                      - redis-server
                  args:
                      - --requirepass
                      - $(REDIS_PASSWORD)
                  ports:
                      - name: redis
                        containerPort: 6379
                  volumeMounts:
                      - name: redis-storage
                        mountPath: /data
                  env:
                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: redis-secret-{{ .Values.configVersions.redis }}
                                key: db_password