# Environment Settings
namespace: default
environment: dev
hostname: fastapi.localhost
modelName: "mambaout_model.onnx"

# Config Versions
configVersions:
  modelServer: v1
  redis: v1

# Web Server
webServer:
  image:
    repository: web-server
    tag: latest
    nodeport: 30000

# Model Server
modelServer:
  image:
    repository: model-server
    tag: latest
  resources:
    memory: "2Gi"
    cpu: "1000m"

# Redis
redis:
  image:
    repository: redis
    tag: 7.4.1
  resources:
    memory: "200Mi"
    cpu: "200m"
  password: "default-password"


